### PR TITLE
fix cart

### LINKED ISSUE #224: Implement Delivery Component
image
image

image

- Need to create the input components and ensure there is a user object and everything gets handled correctly
- This issue handles UI and the logic to capture the user input

### PR DESCRIPTION
**Pull request by menthy-wu**
image
image
image

### CODE REVIEW

File: src/components/Input.jsx [hunk 1]
```diff
@@ -0,0 +1,16 @@
+const Input = ({ object, setObject, field, text, placeholder }) => {
+  return (
+    <div className="w-full">
+      <div className="font-medium text-sm mb-1">{text}</div>
+      <input
+        className="border border-parts-gray-400 rounded w-full bg-transparent px-2 py-1"
+        type="text"
+        placeholder={placeholder}
+        value={object[field]}
+        onChange={(e) => setObject({ ...object, [field]: e.target.value })}
```
Comment (shahdivyank) [inline src/components/Input.jsx]: on change should be handled in parent and just passed down, this caused a bunch of problems later on with hackathon website :sob:

File: src/components/Radio.jsx [hunk 2]
```diff
@@ -0,0 +1,31 @@
...
+const Radio = ({ object, setObject, field, text, options }) => {
+  return (
+    <div className="w-full">
+      <div className="font-medium text-sm mb-1">{text}</div>
+      <div className="w-full grid grid-cols-2 gap-4">
+        {options.map((option, index) => (
+          <div
+            key={index}
+            className="border border-parts-gray-400 rounded w-full bg-transparent cursor-pointer flex justify-between items-start p-4"
+            onClick={() => setObject({ ...object, [field]: option.text })}
```
Comment (shahdivyank) [inline src/components/Radio.jsx]: onchange should be a prop since it can change for other uses

File: src/components/cart/Cart.jsx [hunk 3]
```diff
@@ -3,18 +3,36 @@ import { useState } from "react";
...
+import Header from "./Header";
+import { DELIVERY_FIELDS } from "@/data/cart";
+import { ITEMS } from "@/mock/items";
 
 const Cart = () => {
+  const [items, setItems] = useState(ITEMS);
   const [state, setState] = useState(0);
+  const [deliveryInfo, setDeliveryInfo] = useState({
+    ...Object.fromEntries(DELIVERY_FIELDS.map((k) => [[k.field], ""])),
+    deliveryMethod: "Standard Shipping",
```
Comment (shahdivyank) [inline src/components/cart/Cart.jsx:15]: variables should be one word as much as possible, we can just do delivery

File: src/components/cart/Cart.jsx [hunk 4]
```diff
@@ -3,18 +3,36 @@ import { useState } from "react";
...
+  });
+  const nextState = () => {
+    setState(state + 1);
+    if (state === 1) console.log(items, deliveryInfo);
```
Comment (shahdivyank) [inline src/components/cart/Cart.jsx]: this is unstable code :sob:

File: src/components/cart/Delivery.jsx [hunk 5]
```diff
@@ -1,5 +1,50 @@
-const Delivery = () => {
-  return <div>Delivery</div>;
+import { IoLockClosedOutline } from "react-icons/io5";
+import Input from "../Input";
+import { DELIVERY_FIELDS } from "@/data/cart";
+import Radio from "../Radio";
+import { DELIVERY_METHOD } from "@/data/cart";
+
+const Delivery = ({ state, deliveryInfo, setDeliveryInfo }) => {
```
Comment (shahdivyank) [inline src/components/cart/Delivery.jsx]: delivery, setDelivery

File: src/components/Input.jsx [hunk 6]
```diff
@@ -0,0 +1,16 @@
+const Input = ({ object, setObject, field, text, placeholder, onChange }) => {
+  return (
+    <div className="w-full">
+      <div className="font-medium text-sm mb-1">{text}</div>
+      <input
+        className="border border-parts-gray-400 rounded w-full bg-transparent px-2 py-1"
+        type="text"
+        placeholder={placeholder}
+        value={object[field]}
```
Comment (shahdivyank) [inline src/components/Input.jsx]: just have a value as well, this is risky

File: src/components/Input.jsx [hunk 7]
```diff
@@ -0,0 +1,16 @@
+const Input = ({ object, setObject, field, text, placeholder, onChange }) => {
```
Comment (shahdivyank) [inline src/components/Input.jsx]: setObject is unused?!

File: src/components/cart/Cart.jsx [hunk 8]
```diff
@@ -15,15 +19,29 @@ const Cart = () => {
     }
   }, []);
   const [state, setState] = useState(0);
+  const [delivery, setDelivery] = useState({
+    ...Object.fromEntries(DELIVERY_FIELDS.map((k) => [[k.field], ""])),
+    deliveryMethod: "Standard Shipping",
+  });
+  const nextState = () => {
+    if (state === 1) console.log(items, delivery);
```
Comment (shahdivyank) [inline src/components/cart/Cart.jsx]: remove console logs

**Review by shahdivyank — APPROVED** [review]
